### DISCUSSION TITLE
Sfdx-Hardis Delta deployments unable to fetch target branch

### DISCUSSION THREAD

**Discussion by jarjo** [hardisgroupcom/sfdx-hardis#570] [Q&A]
Hi
I have been migrating a project from a selfbuilt cicd in bitbucket to sfdx hardis. Full deploys seems to work correctly, However if i try to enable delta deploys from a feature branch to an major branch im running into the issue below, The pipeline still finishes successfully with a full deploy instead of an delta. 

I have set it up in accordance to the setup guide over at https://sfdx-hardis.cloudity.com/salesforce-ci-cd-setup-git/. My gitignore is more or less standard and the sfdx-hardis files are all synced to the branch in question.

Any ideasas to why it cannot find the branch names?

```sh
+ sfdx hardis:project:deploy:sources:dx --check

[sfdx-hardis][command] sfdx force:org:display --targetusername integration --json

[sfdx-hardis] You are already connected as 'censored' on org 'censored'

[sfdx-hardis][command] sfdx config:set defaultusername='censored' --json

[sfdx-hardis] To use sfdx-hardis GitProvider capabilities, SYSTEM_ACCESSTOKEN, CI_JOB_TOKEN or GITHUB_TOKEN must be accessible for Azure Pipelines, Gitlab or GitHub

[sfdx-hardis] Computing commits summary...

[sfdx-hardis] To use sfdx-hardis GitProvider capabilities, SYSTEM_ACCESSTOKEN, CI_JOB_TOKEN or GITHUB_TOKEN must be accessible for Azure Pipelines, Gitlab or GitHub

[sfdx-hardis][command] git fetch origin undefined:undefined

[sfdx-hardis] [Warning] Unable to fetch target branch undefined to prepare call to sfdx-git-delta

{"task":{"commands":["fetch","origin","undefined:undefined"],"format":"utf-8"}}

[sfdx-hardis][command] git fetch origin integration:integration

[sfdx-hardis][command] git log --pretty=format:òòòòòò %H ò %aI ò %s ò %D ò %b ò %aN ò %aE òò undefined..integration

[sfdx-hardis] Unable to compute git summary:

Error: fatal: ambiguous argument 'undefined..integration': unknown revision or path not in the working tree.

Use '--' to separate paths from revisions, like this:

'git <command> [<revision>...] -- [<file>...]'
```

**Comment by nvuillam** [comment]
@jarjo the bitbucket integration is the one I played less with, but @derroman is an expert and probably can help you !
(Otherwise we'll find a solution anyway !)

Meanwhile, I suggest you disable the delta mode by defining either
- `useDeltaDeployment: false` in `config/.sfdx-hardis.yml`
- env variable `USE_DELTA_DEPLOYMENT=false`

Note: I edited your question to add 3 quotes to display code/console on multiline with GitHub Markdown :)

**Comment by derroman** [comment]
Hi there.

based on the error message provided it seems to not be an issue of bitbucket in the first place... 

`Error: fatal: ambiguous argument 'undefined..integration': unknown revision or path not in the working tree.`

Something might be strange with your git history? I am not that of an Git expert and I also did not invest much time in delta comparisons yet... 

Did you update / change the bitbucket pipeline yml based on your personal needs? (Not needed, just asking, if you did.) If so, could you share it?

**Reply by nvuillam** [reply]
@derroman are you successfully  using delta deployments on your bitbucket projects ?

**Comment by jarjo** [comment]
Something might be a bit strange with it but i dont really understand what it would be. Worth digging into a bit more though. 

Yeah it its edited but only slightly. I have basically changed a branch and commented out megalinter.

```# You might add new branch names in pipeline "branches"
image: node:18
definitions:
    services:
        docker:
            memory: 3072

pipelines:
    # Check jobs on pull requests
    pull-requests:
        "**":
            - parallel:
                  # Run MegaLinter
                  #- step:
                  #      name: Run MegaLinter
                  #      image: oxsecurity/megalinter-salesforce:latest
                  #      script:
                  #          - export DEFAULT_WORKSPACE=$BITBUCKET_CLONE_DIR && bash /entrypoint.sh
                  #      artifacts:
                  #          - megalinter-reports/**
                  # Simulate deployment
                  - step:
                        name: Simulate SFDX deployment
                        script:
                            - npm install --no-cache @salesforce/cli --global
                            - sf plugins install @salesforce/plugin-packaging
                            - echo 'y' | sfdx plugins:install sfdx-hardis
                            - echo 'y' | sfdx plugins:install sfdx-essentials
                            - echo 'y' | sfdx plugins:install sfdx-git-delta
                            - sf version --verbose --json
                            - export BRANCH_NAME=$(echo "$BITBUCKET_PR_DESTINATION_BRANCH" | sed 's/refs\/heads\///')
                            - export CI_COMMIT_REF_NAME=$BRANCH_NAME
                            - export ORG_ALIAS=$BRANCH_NAME
                            - export CONFIG_BRANCH=$BRANCH_NAME
                            - export FORCE_COLOR=1
                            - sfdx hardis:auth:login
                            - sfdx hardis:project:deploy:sources:dx --check

    branches:
        # Add all your major branches here
        "{integration,preprod,master}":
            - step:
                  name: Deploy to major org
                  script:
                      - npm install --no-cache @salesforce/cli --global
                      - sf plugins install @salesforce/plugin-packaging
                      - echo 'y' | sfdx plugins:install sfdx-hardis
                      - echo 'y' | sfdx plugins:install sfdx-essentials
                      - echo 'y' | sfdx plugins:install sfdx-git-delta
                      - sf version --verbose --json
                      - export BRANCH_NAME=$(echo "$BITBUCKET_BRANCH" | sed 's/refs\/heads\///')
                      - export CI_COMMIT_REF_NAME=$BRANCH_NAME
                      - export CONFIG_BRANCH=$BRANCH_NAME
                      - export ORG_ALIAS=$BRANCH_NAME
                      - export FORCE_COLOR=1
                      - sfdx hardis:auth:login
                      - sfdx hardis:project:deploy:sources:dx
```

**Reply by nvuillam** [reply]
@jarjo thanks for the details, it will help :)
Would it be also possible to have the config/.sfdx-hardis.yml ?

**Comment by jarjo** [comment]
@nvuillam  Yep ill include the personal one as well if it helps 
```
installedApps:
    - git
    - openssl
developmentBranch: integration
localStorageBranchTargets:
    features/config/cicdhardis: integration
scratchOrgAlias: null
scratchOrgUsername: null
sfdxPluginsStdout: "packaging \e[2m2.1.12\e[22m\nsalesforce-app \e[2m1.0.0\e[22m\e[2m (link)\e[22m C:\\Users\\jarjo\\source\\map-salesforce-core\nsfdmu \e[2m4.33.4\e[22m\nsfdx-essentials \e[2m2.12.0\e[22m\nsfdx-git-delta \e[2m5.34.0\e[22m\nsfdx-hardis \e[2m4.28.4\e[22m\nsignups \e[2m2.0.28\e[22m\e[2m (2.0.28)\e[22m\ntexei-sfdx-plugin \e[2m2.3.3\e[22m\n\e[2m\e[22m\n\e[2mUninstalled JIT Plugins:\e[22m\ncommunity \e[2m3.0.25\e[22m\ncustom-metadata \e[2m3.1.16\e[22m\ndev \e[2m2.1.13\e[22m\ndevops-center \e[2m1.2.8\e[22m\nenv \e[2m3.0.25\e[22m\nfunctions \e[2m1.23.0\e[22m\n@salesforce/sfdx-plugin-lwc-test \e[2m1.2.0\e[22m\n@salesforce/sfdx-scanner \e[2m3.22.0\e[22m\n"
mergeRequests:
    - branch: features/config/cicdhardis

```

```
useDeltaDeployment: true
installedPackages:
  - Id: 0A32p000000cNEKCA2
    SubscriberPackageId: 03330000000wDAbAAM
    SubscriberPackageName: Salesforce Connected Apps
    SubscriberPackageNamespace: sf_com_apps
    SubscriberPackageVersionId: 04t30000001DUvrAAG
    SubscriberPackageVersionName: Winter '16
    SubscriberPackageVersionNumber: 1.7.0.1
    installOnScratchOrgs: false
    installDuringDeployments: false
  - Id: 0A32p000000uylFCAQ
    SubscriberPackageId: 03330000001Ig8MAAS
    SubscriberPackageName: Salesforce Mobile Apps
    SubscriberPackageNamespace: sf_chttr_apps
    SubscriberPackageVersionId: 04t3A000001DdcGQAS
    SubscriberPackageVersionName: Winter 2021
    SubscriberPackageVersionNumber: 1.20.0.1
    installOnScratchOrgs: false
    installDuringDeployments: false
  - Id: 0A32p000000tTx7CAE
    SubscriberPackageId: 03350000000DFFrAAO
    SubscriberPackageName: Salesforce.com CRM Dashboards
    SubscriberPackageNamespace: null
    SubscriberPackageVersionId: 04t50000000EcdrAAC
    SubscriberPackageVersionName: Summer 2011
    SubscriberPackageVersionNumber: 1.0.0.1
    installOnScratchOrgs: false
    installDuringDeployments: false
  - Id: 0A32p000000ck2tCAA
    SubscriberPackageId: 0335Y000000BLtoQAG
    SubscriberPackageName: Salesforce Standard Data Model
    SubscriberPackageNamespace: ssot
    SubscriberPackageVersionId: 04t5Y000001MkDtQAK
    SubscriberPackageVersionName: '1.40'
    SubscriberPackageVersionNumber: 1.40.0.1
    installOnScratchOrgs: false
    installDuringDeployments: false
  - Id: 0A32p000000ck4aCAA
    SubscriberPackageId: 0335w000000EfskAAC
    SubscriberPackageName: Tableau Viz Lightning Web Component
    SubscriberPackageNamespace: tab
    SubscriberPackageVersionId: 04t5w000005PmeOAAS
    SubscriberPackageVersionName: February 2023
    SubscriberPackageVersionNumber: 1.3.0.3
    installOnScratchOrgs: false
    installDuringDeployments: false
  - Id: 0A32p000000gLoBCAU
    SubscriberPackageId: 03361000000PjzmAAC
    SubscriberPackageName: MarketingCloudConnectedApp
    SubscriberPackageNamespace: MCCA5PROD
    SubscriberPackageVersionId: 04t61000000gWo1AAE
    SubscriberPackageVersionName: Spring 2017
    SubscriberPackageVersionNumber: 1.5.0.3
    installOnScratchOrgs: false
    installDuringDeployments: false
  - Id: 0A32p000000ck6bCAA
    SubscriberPackageId: 0336S000000spIBQAY
    SubscriberPackageName: CDPAdvertising
    SubscriberPackageNamespace: cdpactvstrgptnr
    SubscriberPackageVersionId: 04t6S000001MT9AQAW
    SubscriberPackageVersionName: '248.10'
    SubscriberPackageVersionNumber: 2.4.0.1
    installOnScratchOrgs: false
    installDuringDeployments: false
  - Id: 0A32p000000ck38CAA
    SubscriberPackageId: 033B000000021ZYIAY
    SubscriberPackageName: Sales Cloud
    SubscriberPackageNamespace: cdp_crm_dk1
    SubscriberPackageVersionId: 04tB0000000BYKvIAO
    SubscriberPackageVersionName: Spring 2022
    SubscriberPackageVersionNumber: 1.1.0.1
    installOnScratchOrgs: false
    installDuringDeployments: false
  - Id: 0A32p000000gLebCAE
    SubscriberPackageId: 033i0000000LVMYAA4
    SubscriberPackageName: Marketing Cloud
    SubscriberPackageNamespace: et4ae5
    SubscriberPackageVersionId: 04t6S000000pDpjQAE
    SubscriberPackageVersionName: Marketing Cloud
    SubscriberPackageVersionNumber: 246.1.0.2
    installOnScratchOrgs: false
    installDuringDeployments: false
deploymentPlan:
  packages: []
```

**Reply by nvuillam** [reply]
@jarjo please can you start by adding the following in your .sfdx-hardis.yml file ?

```yaml
projectName: YourProjectName
developmentBranch: integration
allowedOrgTypes:
  - sandbox # keep the values you want
  - scratch # keep the values you want
useDeltaDeployment: false # Use false just to check first if it works without delta
installPackagesDuringCheckDeploy: true # Keep it if you want, otherwise new packages will have to be installed manually ^^
autoCleanTypes:
  - minimizeProfiles # Keep only if it is a build projet, not an existing one with many profiles with rights
  - destructivechanges
  - checkPermissions  # Keep only if your current sources are not too messy, or after have cleaned them ^^
```

**Reply by jarjo** [reply]
added those lines. Im still getting the same issue weirdly enough, even with useDeltaDeployment: false. Is it expected to run those commands for all deploys?

The check only deploy finishes correctly though as it does when i use delta:true. The new values for sfdx-hardis.yml is in the pull request.

```
+ sfdx hardis:project:deploy:sources:dx --check

[sfdx-hardis][command] sfdx force:org:display --targetusername integration --json

[sfdx-hardis] You are already connected as *censored* on org *censored* 

[sfdx-hardis][command] sfdx config:set defaultusername=*censored* --json

- [sfdx-hardis][command] sfdx force:package:installed:list -u *censored* --json

✔ [sfdx-hardis][command] sfdx force:package:installed:list -u *censored* --json

[sfdx-hardis] 
  "status": 0,

  "result": [
*apps* 

  "warnings": [

    "The \"-u\" flag has been deprecated. Use \"--target-org | -o\" instead."

  ]

}

[sfdx-hardis] Skip installation of Salesforce Connected Apps as it is already installed

[sfdx-hardis] Skip installation of Salesforce Mobile Apps as it is already installed

[sfdx-hardis] Skip installation of [Salesforce.com](http://salesforce.com/) CRM Dashboards as it is already installed

[sfdx-hardis] Skip installation of Salesforce Standard Data Model as it is configured to not be installed on scratch orgs

[sfdx-hardis] Skip installation of Tableau Viz Lightning Web Component as it is already installed

[sfdx-hardis] Skip installation of MarketingCloudConnectedApp as it is already installed

[sfdx-hardis] Skip installation of CDPAdvertising as it is already installed

[sfdx-hardis] Skip installation of Sales Cloud as it is already installed

[sfdx-hardis] Skip installation of Marketing Cloud as it is configured to not be installed on scratch orgs

[sfdx-hardis] To use sfdx-hardis GitProvider capabilities, SYSTEM_ACCESSTOKEN, CI_JOB_TOKEN or GITHUB_TOKEN must be accessible for Azure Pipelines, Gitlab or GitHub

[sfdx-hardis] Computing commits summary...

[sfdx-hardis] To use sfdx-hardis GitProvider capabilities, SYSTEM_ACCESSTOKEN, CI_JOB_TOKEN or GITHUB_TOKEN must be accessible for Azure Pipelines, Gitlab or GitHub

[sfdx-hardis][command] git fetch origin undefined:undefined

[sfdx-hardis] [Warning] Unable to fetch target branch undefined to prepare call to sfdx-git-delta

{"task":{"commands":["fetch","origin","undefined:undefined"],"format":"utf-8"}}

[sfdx-hardis][command] git fetch origin integration:integration

[sfdx-hardis][command] git log --pretty=format:òòòòòò %H ò %aI ò %s ò %D ò %b ò %aN ò %aE òò undefined..integration

[sfdx-hardis] Unable to compute git summary:

Error: fatal: ambiguous argument 'undefined..integration': unknown revision or path not in the working tree.

Use '--' to separate paths from revisions, like this:

'git <command> [<revision>...] -- [<file>...]'

[sfdx-hardis] Handling package-no-overwrite.xml...

[sfdx-hardis] Generating full package.xml from target org to identify its items matching with package-no-overwrite.xml ...

- [sfdx-hardis][command] sfdx force:source:manifest:create --manifestname packageTargetOrg.xml --outputdir /tmp/sfdx-hardis-2iy9l --includepackages managed,unlocked --fromorg *censored* 

✔ [sfdx-hardis][command] sfdx force:source:manifest:create --manifestname packageTargetOrg.xml --outputdir /tmp/sfdx-hardis-2iy9l --includepackages managed,unlocked --fromorg *censored* 

[sfdx-hardis] successfully wrote packageTargetOrg.xml to /tmp/sfdx-hardis-2iy9l

[sfdx-hardis] Keeping packageTargetOrg.xml items matching with package-no-overwrite.xml (and remove the rest)...

[sfdx-hardis] Found wildcard * on type ConnectedApp, kept items: 8

[sfdx-hardis] Found wildcard * on type CustomApplication, kept items: 20

[sfdx-hardis] Found wildcard * on type Dashboard, kept items: 11

[sfdx-hardis] Found wildcard * on type Profile, kept items: 18

[sfdx-hardis] Found wildcard * on type Report, kept items: 181

[sfdx-hardis] calculated-package-no-overwrite.xml with only items that already exist in target org: /tmp/sfdx-hardis-2iy9l/calculated-package-no-overwrite.xml

[sfdx-hardis] Removing calculated-package-no-overwrite.xml items from calculated-package.xml...

[sfdx-hardis] Processing split deployments build from deployment plan...

[sfdx-hardis] [

  {

    "label": "calculated-package-xml",

    "packageXmlFile": "/tmp/sfdx-hardis-0bg9qs/calculated-package.xml"

  }

]

[sfdx-hardis] Simulating deployment of calculated-package-xml package: /tmp/sfdx-hardis-0bg9qs/calculated-package.xml ...

- [sfdx-hardis][command] sfdx force:source:deploy -x "/tmp/sfdx-hardis-0bg9qs/calculated-package.xml" --wait 60 --ignorewarnings --testlevel RunLocalTests --postdestructivechanges [./manifest/destructiveChanges.xml](https://bitbucket.org/*censored*/map-salesforce-core/src/e32f6003487d90b281860e0c4ce429cade124c5a/manifest/destructiveChanges.xml) --targetusername *censored* --checkonly --verbose --coverageformatters json-summary

✔ [sfdx-hardis][command] sfdx force:source:deploy -x "/tmp/sfdx-hardis-0bg9qs/calculated-package.xml" --wait 60 --ignorewarnings --testlevel RunLocalTests --postdestructivechanges [./manifest/destructiveChanges.xml](https://bitbucket.org/*censored*/map-salesforce-core/src/e32f6003487d90b281860e0c4ce429cade124c5a/manifest/destructiveChanges.xml) --targetusername *censored* --checkonly --verbose --coverageformatters json-summary

[sfdx-hardis] Deploying v59.0 metadata to *censored* using the v60.0 SOAP API.

=== Deployed Source
```

**Reply by nvuillam** [reply]
@jarjo according to your log, the behaviour is correct, don't be frightened by the warnings (I'll handle them), at worse it impacts notifications content about list of JIRA tickets found in the commits / messages / PRs

Can you use without delta for now and we'll close the issue once I'll have found a solution ?

**Reply by jarjo** [reply]
yep thats no issue for me. I just thought it was weird that it tried to do a delta calc even when delta was set to false. Thanks for the quick reply and help

**Reply by nvuillam** [reply]
@jarjo where in the log do you see it tries delta when you have deltaDeployment=false ?

**Reply by jarjo** [reply]
@nvuillam nvm im guessing its just prepping a summary since there is a lack of any "cannot delta deploy" messages.

**Reply by nvuillam** [reply]
@jarjo what are the source and target branches of your PR ?

**Reply by jarjo** [reply]
target is integration and source is Features/config/cicd a branch that was created through the "start a new task" button in vscodes implementation of hardis. Sorry for the late reply i missed the notification

**Comment by yan-imensar** [comment]
Hi ! I've got the same issue, i wanted to switch from full to delta on my repo, so I appended `.sfdx-hardis.yml` with `useDeltaDeployment: false`

Here is the result

```
[sfdx-hardis] [DeltaDeployment] Delta allowed between minor branch (iws-opportunity-reorg) and major branch (null): using delta deployment mode
[sfdx-hardis] To benefit from Gitlab advanced integration, you need to :
- Go to Settings -> Access tokens -> create a project token named "SFDX HARDIS BOT" with developer access and scope "api", then copy its value
- Go to Settings -> CI/CD -> Variables -> Create a masked variable named CI_SFDX_HARDIS_GITLAB_TOKEN, and paste the access token value
[sfdx-hardis][command] git fetch origin undefined:undefined
[sfdx-hardis] [Warning] Unable to fetch target branch undefined to prepare call to sfdx-git-delta
{"task":{"commands":["fetch","origin","undefined:undefined"],"format":"utf-8"}}
[sfdx-hardis][command] git log --pretty=format:òòòòòò %H ò %aI ò %s ò %D ò %b ò %aN ò %aE òò undefined..iws-opportunity-reorg
Error (1): fatal: ambiguous argument 'undefined..iws-opportunity-reorg': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

Edit : Happens on Gitlab, when pushing on merge request with major org as a target, here is the yaml
```
---
##################################################################
# Test and deployment pipeline for a Salesforce CI/CD Project    #
#         Update it only if you know what you are doing :)       #
##################################################################

# More info at https://sfdx-hardis.cloudity.com/salesforce-ci-cd-setup-home/

# To add custom behaviors, please use side config file .gitlab-ci-config.yml
include:
  - local: ".gitlab-ci-config.yml"

# Pipeline stages
stages:
  - build
  - check_deploy # Simulate deployment to target branch
  - deploy # After a merge, automatically deploys the new commit state into the related Salesforce org

# Jobs are run on sfdx-hardis image, that includes all required dependencies.
# You can use latest, beta or latest-recommended
image: hardisgroupcom/sfdx-hardis:latest

# Force color for output logs for better readability
variables:
  FORCE_COLOR: "1"

check_deploy_to_target_branch_org:
  stage: build
  only:
    refs:
      - merge_requests
      - web
  except:
    variables:
      - $SCRATCH_ORG_POOL == "true"
  interruptible: true
  variables:
    CONFIG_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    ORG_ALIAS: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  script:
    - '[ -z "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" ] && exit 0;' # Skip this job if it is launched from web UI and we are not in merge request context
    - sf hardis:auth:login
    - sf hardis:project:deploy:smart --check


# Simulate deployment to related org
# Is triggered only when scheduled, or via manual launch
check_deploy_to_current_branch_org:
  stage: check_deploy
  only:
    - schedules
    - web
  except:
    variables:
      - $CI_COMMIT_REF_NAME !~ $DEPLOY_BRANCHES
      - $SCRATCH_ORG_POOL == "true"
  interruptible: true
  script:
    - sf hardis:auth:login
    - sf hardis:project:deploy:smart --check

# Deploy to branch related org when detecting new commit (after a merged merge request)
# Don't forget to define variable DEPLOY_BRANCHES to match your branches in .gitlab-ci-config.yml
deploy_to_org:
  stage: deploy
  only:
    - pushes
    - web
  except:
    variables:
      - $CI_COMMIT_REF_NAME !~ $DEPLOY_BRANCHES
      - $SCRATCH_ORG_POOL == "true"
  interruptible: true
  script:
    - sf hardis:auth:login
    - sf hardis:project:deploy:smart
```
