### DISCUSSION TITLE
Deployment plan still looks for a default package.xml

### DISCUSSION THREAD

**Discussion by gintoMathew** [hardisgroupcom/sfdx-hardis#650] [General]
**Issue**
I have set deployment plan with multiple package xmls; but when the pipeline executes, it errors out saying 'no such file or directory, open ./config/package.xml'

Here is how the .sfdx-hardis-yml looks like

```
projectName: hardisPOC
developmentBranch: dev_poc
deploymentPlan:
  packages:
    - label: Package One
      packageXmlFile: manifest/package-one.xml
      order: 1
    - label: Package Two
      packageXmlFile: manifest/package-two.xml
      order: 2
```

**Command executed**
`sfdx hardis:project:deploy:sources:dx --check --testlevel RunRepositoryTests --debug`

**Expected**
According to the documentation the [deploy](https://sfdx-hardis.cloudity.com/hardis/project/deploy/sources/dx/) command, a default package.xml is not needed and the xmls in the deploymentPlan will be used to create a 'calculated-package.xml' for the deployment.

**Additional Note**
Does this command support deployment from a multi package source i.e, 'force-app' is broken into different projects with separate components.

**Comment by nvuillam** [comment]
@gintoMathew the default manifest/package.xml is looked for by default (and it added in the deployment plan with "0" position)

You can solve the issue by using such configuration:

```yaml
projectName: hardisPOC
developmentBranch: dev_poc
deploymentPlan:
  packages:
    - label: Package One
      packageXmlFile: manifest/package.xml
      order: 0
    - label: Package Two
      packageXmlFile: manifest/package-two.xml
      order: 2
```

or even the following (the result will be the same, as manifest/package.xml is implicitely added 

```yaml
projectName: hardisPOC
developmentBranch: dev_poc
deploymentPlan:
  packages:
    - label: Package Two
      packageXmlFile: manifest/package-two.xml
      order: 2
```

If for some reason you don't want to have a main manifest/package.xml, please explain your use case and we'll see if we can make an update that will allow the command to work without it :)
