### DISCUSSION TITLE
Where should I add env variables (ALWAYS_ENABLE_DELTA_DEPLOYMENT)?

### DISCUSSION THREAD

**Discussion by olavozapata** [hardisgroupcom/sfdx-hardis#768] [General]
Hi I'm trying to use the ALWAYS_ENABLE_DELTA_DEPLOYMENT=true

But following the documentation wasn't very clear where.
I tryed on process-deploy.yml

```
      # Set env branch variable (github.ref_name seems to not work)
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      # Login & check deploy with test classes & code coverage
      - name: Login & Process Deployment
        env:
          SFDX_CLIENT_ID_HOMOLOG: ${{ secrets.SFDX_CLIENT_ID_HOMOLOG}}
          SFDX_CLIENT_KEY_HOMOLOG: ${{ secrets.SFDX_CLIENT_KEY_HOMOLOG}}
          SFDX_CLIENT_ID_MASTER: ${{ secrets.SFDX_CLIENT_ID_MASTER}}
          SFDX_CLIENT_KEY_MASTER: ${{ secrets.SFDX_CLIENT_KEY_MASTER}}
          ALWAYS_ENABLE_DELTA_DEPLOYMENT: true
```

but doesn't work (still running the full tests)

Could someone help?

**Comment by nvuillam** [comment]
@olavozapata I never personnally used the `ALWAYS_ENABLE_DELTA_DEPLOYMENT=true` because I consider relevant to make full deployments betweem major orgs, but it should work !

- define `useDeltaDeployment: true` in your `config/.sfdx-hardis.yml` (this is the base prop to activate delta)
- Also define `ALWAYS_ENABLE_DELTA_DEPLOYMENT=true` in check-deploy.yml & process-deploy.xml , in the step calling sfdx hardis:project:deploy:sources:dx --check , that will force the delta even if it's not recommended to use it when deploying to some orgs

Please let me know the results :)

**Reply by olavozapata** [reply]
Hi @nvuillam thanks for your response

Let me see if I understood.

Need to be like this:

sfdx hardis:project:deploy:sources:dx ALWAYS_ENABLE_DELTA_DEPLOYMENT=true --check

??
Thanks

**Reply by nvuillam** [reply]
You can try the following in both check-deploy & process-deploy.yml :)

```yaml
      # Set env branch variable (github.ref_name seems to not work)
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      # Login & check deploy with test classes & code coverage
      - name: Login & Process Deployment
        env:
          SFDX_CLIENT_ID_HOMOLOG: ${{ secrets.SFDX_CLIENT_ID_HOMOLOG}}
          SFDX_CLIENT_KEY_HOMOLOG: ${{ secrets.SFDX_CLIENT_KEY_HOMOLOG}}
          SFDX_CLIENT_ID_MASTER: ${{ secrets.SFDX_CLIENT_ID_MASTER}}
          SFDX_CLIENT_KEY_MASTER: ${{ secrets.SFDX_CLIENT_KEY_MASTER}}
          USE_DELTA_DEPLOYMENT=true
          ALWAYS_ENABLE_DELTA_DEPLOYMENT: true
```
