### ISSUE TITLE
Exclude AI cache pages from search

### ISSUE THREAD

**Issue by nvuillam** [hardisgroupcom/sfdx-hardis#1029]
```yaml
plugins:
  - search
  - exclude-search:
      exclude:
        - page.md
        - page.md#section
        - directory/*
        - /*/page.md
```

pip install mkdocs-exclude-search

https://squidfunk.github.io/mkdocs-material/blog/2021/09/26/excluding-content-from-search/#:~:text=but%20complements%20it.-,Excluding%20pages,%2D%2D%2D%20%23%20Page%20title%20...
