### ISSUE TITLE
SGD delta generation does not generates a package.xml

### ISSUE THREAD

**Issue by szymon-halik** [hardisgroupcom/sfdx-hardis#1130]
Having the following config: 
```yml
name: 'Build'
on:
  pull_request:
    branches:
      - main
      - qa
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  verify_gates:
    uses: org/org-repo/.github/workflows/quality-gates.yml@main
  verify_deployment:
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    needs: verify_gates
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repo'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: 'Restore node_modules cache'
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ env.cache-name }}-
            npm-
      - name: 'Install npm dependencies'
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci
      - name: 'Link plugin'
        run: npm run link:hardis:plugin
      - name: 'Login and verify deployment'
        env:
          SFDX_CLIENT_ID_QA: ${{ secrets.SFDX_CLIENT_ID_QA }}
          SFDX_CLIENT_KEY_QA: ${{ secrets.SFDX_CLIENT_KEY_QA }}
          SFDX_CLIENT_ID_MAIN: ${{ secrets.SFDX_CLIENT_ID_MAIN}}
          SFDX_CLIENT_KEY_MAIN: ${{ secrets.SFDX_CLIENT_KEY_MAIN}}
          SFDX_DEPLOY_WAIT_MINUTES: 120 # Override if necessary
          SFDX_TEST_WAIT_MINUTES: 120 # Override if necessary
          CI_COMMIT_REF_NAME: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
          ORG_ALIAS: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
          CONFIG_BRANCH: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_TICKET_REGEX: ${{ secrets.JIRA_TICKET_REGEX }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FORCE_COLOR: '1'
          SFDX_DISABLE_FLOW_DIFF: false # Set to true to disable Flow doc during CI/CD
          ALWAYS_ENABLE_DELTA_DEPLOYMENT: true
          USE_DELTA_DEPLOYMENT_AFTER_MERGE: true
          USE_DELTA_DEPLOYMENT: true
        run: |
          echo "Simulate SFDX deployment using Hardis against \"$CONFIG_BRANCH\""
          npx sf hardis auth login
          npx sf hardis project deploy smart --check

      - name: 'List temp'
        if: always()
        run: |
          # Find all sfdx-hardis temp directories
          TEMP_DIRS=$(find /tmp -maxdepth 1 -type d -name "sfdx-hardis-*")

          if [ -z "$TEMP_DIRS" ]; then
            echo "No sfdx-hardis temporary directories found in /tmp"
          else
            echo "Found the following sfdx-hardis temp directories:"
            echo "$TEMP_DIRS"

            # Loop through each directory and list its contents
            for DIR in $TEMP_DIRS; do
              echo "==================================================="
              echo "Contents of $DIR:"
              ls -la "$DIR"

              echo "Full directory structure of $DIR:"
              find "$DIR" -type f -o -type d | sort

              echo "Checking for package directory in $DIR:"
              if [ -d "$DIR/package" ]; then
                echo "package directory exists"
                ls -la "$DIR/package/"
              else
                echo "package directory does not exist"
              fi
            done
          fi

```
And `.sfdx-hardis.yml`
```yml
projectName: PIAB
devHubAlias: DevHub
developmentBranch: main
allowedOrgTypes:
  - sandbox
availableTargetBranches:
  - main
  - qa
devHubUsername: ci.integration@org.com
skipUpdateGitIgnore: true
skipUpdateForceIgnore: true
```

No, `package.xml` found in temp dirs 
```txt
Found the following sfdx-hardis temp directories:
/tmp/sfdx-hardis-hecjo
/tmp/sfdx-hardis-zf4igd
===================================================
Contents of /tmp/sfdx-hardis-hecjo:
total 20
drwxr-xr-x  2 runner docker  4096 Mar 20 12:08 .
drwxrwxrwt 17 root   root   12288 Mar 20 12:09 ..
-rw-r--r--  1 runner docker  1704 Mar 20 12:08 main.key
Full directory structure of /tmp/sfdx-hardis-hecjo:
/tmp/sfdx-hardis-hecjo
/tmp/sfdx-hardis-hecjo/main.key
Checking for package directory in /tmp/sfdx-hardis-hecjo:
package directory does not exist
===================================================
Contents of /tmp/sfdx-hardis-zf4igd:
total 20
drwxr-xr-x  3 runner docker  4096 Mar 20 12:09 .
drwxrwxrwt 17 root   root   12288 Mar 20 12:09 ..
drwxr-xr-x  2 runner docker  4096 Mar 20 12:09 package
Full directory structure of /tmp/sfdx-hardis-zf4igd:
/tmp/sfdx-hardis-zf4igd
/tmp/sfdx-hardis-zf4igd/package
/tmp/sfdx-hardis-zf4igd/package/packageDelta.xml
Checking for package directory in /tmp/sfdx-hardis-zf4igd:
package directory exists
total 364
drwxr-xr-x 2 runner docker   4096 Mar 20 12:09 .
drwxr-xr-x 3 runner docker   4096 Mar 20 12:09 ..
-rw-r--r-- 1 runner docker 361479 Mar 20 12:09 packageDelta.xml
```
Deployment fails with the following error:
`ENOENT: no such file or directory, open '/tmp/sfdx-hardis-zf4igd/package/package.xml'`
