### ISSUE TITLE
delta deployments on bitbucket - refuse to fetch branch

### ISSUE THREAD

**Issue by gabeclarke** [hardisgroupcom/sfdx-hardis#1187]
Hi, I am having an issue with the bitbucket pipeline, the validation and deployments are completed successfully, but when delta deployments are enabled, on this step of the pipeline -
sfdx hardis:project:deploy:sources:dx --check

We are getting this 'Unable to fetch current branch'. I am assuming this is because you can't fetch origin with that command while you have the branch currently checked out or you get this -

fatal: refusing to fetch into branch 'refs/heads/release/sprint-xy.z' checked out at 'repository-location'.

Is there something I am missing here? Below is the relevant snippet of the pipeline running -

BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 

[sfdx-hardis] Computing commits summary...

 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 

[sfdx-hardis][command] git fetch origin main:main

[sfdx-hardis][command] git fetch origin release/sprint-xy.z:release/sprint-xy.z

[sfdx-hardis] [Warning] Unable to fetch current branch release/sprint-xy.z to prepare call to sfdx-git-delta

{"task":{"commands":["fetch","origin","release/sprint-xy.z:release/sprint-xy.z"],"format":"utf-8"}}

[sfdx-hardis][command] git log --pretty=format:òòòòòò %H ò %aI ò %s ò %D ò %b ò %aN ò %aE òò main..release/sprint-xy.z

[sfdx-hardis][command] git merge-base main release/sprint-xy.z

**Comment by nvuillam** [comment]
@gabeclarke please can you try to add the following in your bitbucket-pipelines.yml steps ?

```yaml
clone: 
 depth: full
```

Full step example:

```yaml
          - step:
              name: Simulate SFDX deployment
              clone:
                depth: full
              script:
                - npm install --no-cache @salesforce/cli --global
                - sf plugins install @salesforce/plugin-packaging
                - echo 'y' | sf plugins install sfdx-hardis
                - echo 'y' | sf plugins install sfdx-git-delta
                - sf version --verbose --json
                - export BRANCH_NAME=$(echo "$BITBUCKET_PR_DESTINATION_BRANCH" | sed 's/refs\/heads\///')
                - export CI_COMMIT_REF_NAME=$BRANCH_NAME
                - export ORG_ALIAS=$BRANCH_NAME
                - export CONFIG_BRANCH=$BRANCH_NAME
                - export FORCE_COLOR=1
                - export SFDX_DISABLE_FLOW_DIFF=false # Set to true to disable Flow doc during CI/CD setup
                - sf hardis:auth:login
                - sf hardis:project:deploy:smart --check
```     


@derroman maybe you have seen the issue ?

**Comment by gabeclarke** [comment]
Got the same error, below is the pipeline I ran to test it 

```
pipelines:
  # Check jobs on pull requests
  pull-requests:
    "**":
      - parallel:
          # Run MegaLinter
          - step:
              name: Run MegaLinter
              image: oxsecurity/megalinter-salesforce:latest
              script:
                - export DEFAULT_WORKSPACE=$BITBUCKET_CLONE_DIR && bash /entrypoint.sh
              artifacts:
                - megalinter-reports/**
          # Simulate deployment
          - step:
              name: Simulate SFDX deployment
              clone:
                depth: full
              script:
                - npm install --no-cache @salesforce/cli --global
                - sf plugins install @salesforce/plugin-packaging
                - echo 'y' | sf plugins:install sfdx-hardis
                - echo 'y' | sf plugins:install sfdx-git-delta
                - sf version --verbose --json
                - export BRANCH_NAME=$(echo "$BITBUCKET_PR_DESTINATION_BRANCH" | sed 's/refs\/heads\///')
                - export CI_COMMIT_REF_NAME=$BRANCH_NAME
                - export ORG_ALIAS=$BRANCH_NAME
                - export CONFIG_BRANCH=$BRANCH_NAME
                - export FORCE_COLOR=1
                - export SFDX_DISABLE_FLOW_DIFF=true
                - sfdx hardis:auth:login
                - sfdx hardis:project:deploy:smart --check
```
