### ISSUE TITLE
Org Monitoring Workflow failing at sf hardis:org:monitor:backup with No default environment found

### ISSUE THREAD

**Issue by MattFaz** [hardisgroupcom/sfdx-hardis#822]
Hi,

I've setup the connected app and configured the Github secrets accordingly.
However at the `Login & Retrieve Metadata` step I'm receiving the following error: 

```sh
Monitoring sfdx-hardis: Metadata Backup for "monitoring_squareinc"
[sfdx-hardis][command] git rev-parse --show-toplevel
[sfdx-hardis] hardis:auth:login execution time 0:00:00.355
[sfdx-hardis][command] git rev-parse --show-toplevel
[sfdx-hardis][command] sf org display --target-org monitoring_squareinc --json
Error (NoDefaultEnvError): No default environment found. Use -o or --target-org to specify an environment.
Error: Process completed with exit code 1.
```

![image](https://github.com/user-attachments/assets/26db8f1c-b56e-4fa8-8d06-1fb8accadd4b)

I added a `echo login success` after the `sf hardis:auth:login` command and I appear to be logging successfully.
The issue lies in the `sf hardis:org:monitor:backup` command, I've tried adding a target org as detailed in the [docs](https://sfdx-hardis.cloudity.com/hardis/org/monitor/backup/) with `sf hardis:org:monitor:backup -o $CONFIG_BRANCH` but same error.

Any help would be appreciated. Below is my `.yml` file _(removed all steps after failing step to reduce size)_.
```yml
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

name: Org Monitoring sfdx-hardis

permissions: read-all

jobs:
  ##############################################
  ### Sfdx Sources Backup + Push new commit ####
  ##############################################
  backup:
    runs-on: ubuntu-latest
    name: Backup metadatas
    permissions: write-all
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        # MANUAL: Add your monitored git branches here
        branch:
          - monitoring_squareinc
    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Faster code checkout fetching only latest commit
          ref: ${{ matrix.branch }}
          persist-credentials: true
      # Setup node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      # SFDX & plugins
      - name: Install SFDX and plugins
        run: |
          npm install --no-cache @salesforce/cli --global
          sf plugins install --force @salesforce/plugin-packaging
          echo 'y' | sf plugins install --force sfdx-hardis
          echo 'y' | sf plugins install --force sfdx-git-delta
          sf version --verbose --json
      # Login & check deploy with test classes & code coverage
      - name: Login & Retrieve Metadata
        env:
          # MANUAL: Update variables below to add authentication variables you need
          SFDX_CLIENT_ID_MONITORING_SQUAREINC: ${{ secrets.SFDX_CLIENT_ID_MONITORING_SQUAREINC }}
          SFDX_CLIENT_KEY_MONITORING_SQUAREINC: ${{ secrets.SFDX_CLIENT_KEY_MONITORING_SQUAREINC }}
          SFDX_DEPLOY_WAIT_MINUTES: 120 # Override if necessary
          SFDX_TEST_WAIT_MINUTES: 120 # Override if necessary
          CI_COMMIT_REF_NAME: ${{ matrix.branch }}
          ORG_ALIAS: ${{ matrix.branch }}
          CONFIG_BRANCH: ${{ matrix.branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Monitoring sfdx-hardis: Metadata Backup for \"$CONFIG_BRANCH\""
          sf hardis:auth:login
          sf hardis:org:monitor:backup
```
